name: release

on:
  release:
    types:
      - released # a release or draft of a release is published, or a pre-release is changed to a release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Antlr4
        # You may pin to the exact commit or the version.
        # uses: StoneMoe/setup-antlr4@09efbcfc95838745ee61c14ff0b8ff53144a5edb
        uses: StoneMoe/setup-antlr4@v4.10.1

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: |
          mkdir build && cp *.g4 build/ && pushd build
          echo "Dist of [RoutingA-antlr4](https://github.com/v2rayA/RoutingA-antlr4)\n" > README.md
          antlr4 -Dlanguage=Go -o go/routingA/ -package "routingA" routingA.g4
          antlr4 -Dlanguage=Cpp -o cpp/routingA/ -package "routingA" routingA.g4
          popd
          
      - name: Deploy Release Repository
        if: startsWith(github.ref, 'refs/tags/v')
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          repo: v2rayA/RoutingA-dist
          target_branch: main
          build_dir: build
        env:
            GH_PAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Tag Release Repository
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const commit = await github.rest.repos.getCommit({
              owner: context.repo.owner,
              repo: 'RoutingA-dist',
              ref: 'main'
            });
            try {
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: 'RoutingA-dist',
                ref: context.ref,
                sha: commit.data.sha.toString()
              });
            } catch(e) {
              if ( e instanceof Error && e.status === 422 ) {
                // the tag already exists, force update it
                await github.rest.git.updateRef({
                  owner: context.repo.owner,
                  repo: 'RoutingA-dist',
                  ref: context.ref.replace(/^refs\//, ''),
                  sha: commit.data.sha.toString(),
                  force: true
                });
              };
            };
